# 1: Write a function so that the columns of the output matrix are powers of the input vector. 
# The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 
# HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde. 


In [1]:
import numpy as np
def make_vander(arr,N=None,increasing=False):
    output=None
    if(N==None):
        N=len(arr)
    if(increasing==False):
        output=np.array([[j**(N-i-1) for i in range(N)] for j in arr])
    else:
        output=np.array([[j**(i) for i in range(N)]for j in arr])
    return output
        
if __name__=='__main__':
    arr=np.array(list(map(int,input().split())))
    N=int(input("enter the integer: "))
    output_matrix_1=make_vander(arr,N,True)
    print("when increasing order is true: \n",output_matrix_1)
    output_matrix_2=make_vander(arr,N,False)
    print("when increasing order is false: \n",output_matrix_2)

1 2 3 4 5
enter the integer: 4
when increasing order is true: 
 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
when increasing order is false: 
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]


# 2: Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: 
# The moving average sequence has n-k+1 elements as shown below. 
# The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
#    i    1 2 3 4 5 6 7 8 9 10 
# ===== == == == == == == == == == ==
# Input 10 20 30 40 50 60 70 80 90 100 
# y1 25 = (10+20+30+40)/4 
# y2 35 = (20+30+40+50)/4 
# y3 45 = (30+40+50+60)/4 
# y4 55 = (40+50+60+70)/4 
# y5 65 = (50+60+70+80)/4
# y6 75 = (60+70+80+90)/4
# y7 85 = (70+80+90+100)/4 
# Thus, the moving average sequence has n-k+1=10-4+1=7 values. 
# Question: Write a function to find moving average in an array over a window: 
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 


In [8]:
def moving_average(n,arr,k):
    moving_averages=[]
    for i in range(n-k+1):
        new_arr=arr[i:i+k]
        moving_sum=sum(new_arr)
        moving_averages.append(moving_sum/k)
    return moving_averages
if __name__=="__main__":
    n=int(input("enter the sequence length: "))
    arr=list(map(int,input().split(",")))
    k=int(input("enter the window size: "))
    output=moving_average(n,arr,k)
    print(output)

enter the sequence length: 13
3,5,7,2,8,10,11,65,72,81,99,100,150
enter the window size: 3
[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
